# Generated by Django 5.0.2 on 2024-03-26 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryTaskErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255, verbose_name='Название задачи celery')),
                ('error_message', models.TextField(verbose_name='Сообщение ошибки')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата ошибки')),
            ],
            options={
                'verbose_name': 'Celery Логи',
                'verbose_name_plural': 'Celery Логи',
            },
        ),
        migrations.CreateModel(
            name='InstagramLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=255, verbose_name='Логин')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль')),
            ],
            options={
                'verbose_name': 'Логин для входа',
                'verbose_name_plural': 'Логины для входов',
            },
        ),
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Instagram Post ID')),
                ('post_url', models.URLField(verbose_name='Ссылка на пост')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на изображение')),
                ('description', models.TextField(blank=True, default='Описание отсутствует', verbose_name='Описание')),
                ('count_likes', models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество лайков')),
                ('count_views', models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество просмотров')),
                ('created_instagram', models.DateTimeField(blank=True, null=True, verbose_name='Дата создания поста')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
        migrations.CreateModel(
            name='InstagramComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Instagram Comment ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('username', models.CharField(blank=True, max_length=255, verbose_name='Имя пользователя')),
                ('profile_url', models.URLField(blank=True, verbose_name='Ссылка на профиль')),
                ('created_instagram', models.DateTimeField(blank=True, null=True, verbose_name='Дата создания комментария')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='contacts.instagrampost', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.CreateModel(
            name='InstagramProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Instagram ID')),
                ('username', models.CharField(blank=True, help_text='https://www.instagram.com/codex_kg/', max_length=255, unique=True, verbose_name='Профиль Instagram')),
                ('url', models.URLField(help_text='Здесь будет отображаться профиль Instagram', unique=True, verbose_name='Ссылка на инстаграм профиль')),
                ('profile_image', models.ImageField(blank=True, max_length=500, null=True, upload_to='profile_images/', verbose_name='Фотография профиля')),
                ('count_followers', models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество подписчиков')),
                ('count_posts', models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество постов')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('authorization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorization_profile', to='contacts.instagramlogin', verbose_name='Авторазация аккаунта')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_posts', to='contacts.instagramprofile', verbose_name='Профиль'),
        ),
    ]
