# Generated by Django 5.0.2 on 2024-03-06 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramcomment',
            name='profile_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='instagramcomment',
            name='username',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='instagramprofile',
            name='instagram_password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='instagramprofile',
            name='instagram_username',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
