# Generated by Django 5.0.2 on 2024-03-06 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_instagramcomment_profile_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramprofile',
            name='profile_photo_url',
            field=models.URLField(blank=True),
        ),
    ]
