# Generated by Django 5.0.2 on 2024-03-01 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_instagrampost_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrampost',
            name='post_url',
            field=models.URLField(default=1, verbose_name='Ссылка на публикацию'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.instagramprofile', verbose_name='Профиль'),
        ),
        migrations.DeleteModel(
            name='InstagramComment',
        ),
    ]
