# Generated by Django 5.0.2 on 2024-03-01 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_instagrampost_post_url_alter_instagrampost_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagrampost',
            name='post_url',
        ),
    ]
