# Generated by Django 5.0.2 on 2024-03-06 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_instagramprofile_profile_photo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagramprofile',
            name='profile_photo_url',
        ),
    ]
