# Generated by Django 5.0.2 on 2024-03-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_remove_instagramprofile_profile_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramprofile',
            name='username',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='Профиль Instagram'),
        ),
    ]
