# Generated by Django 5.0.2 on 2024-03-08 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_alter_instagramprofile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagramprofile',
            name='instagram_password',
        ),
        migrations.RemoveField(
            model_name='instagramprofile',
            name='instagram_username',
        ),
    ]
