# Generated by Django 5.0.2 on 2024-03-08 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_remove_instagramprofile_instagram_password_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instagramcomment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='instagrampost',
            options={'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AlterModelOptions(
            name='instagramprofile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
