# Generated by Django 5.0.2 on 2024-03-01 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_instagrampost2_instagramcomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InstagramPost2',
        ),
    ]
