# Generated by Django 5.0.2 on 2024-03-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_alter_instagramcomment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramprofile',
            name='username',
            field=models.CharField(blank=True, help_text='https://www.instagram.com/codex_kg/', max_length=255, unique=True, verbose_name='Профиль Instagram'),
        ),
    ]
