# Generated by Django 5.0.2 on 2024-03-01 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_delete_instagrampost2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instagrampost',
            options={'verbose_name': 'Публикация', 'verbose_name_plural': 'Публикации'},
        ),
        migrations.RemoveField(
            model_name='instagrampost',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='instagrampost',
            name='description',
        ),
        migrations.RemoveField(
            model_name='instagrampost',
            name='image_url',
        ),
        migrations.DeleteModel(
            name='InstagramComment',
        ),
    ]
