# Generated by Django 5.0.2 on 2024-03-01 02:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_alter_instagrampost_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instagrampost',
            options={},
        ),
        migrations.RemoveField(
            model_name='instagrampost',
            name='profile',
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='post_url',
            field=models.URLField(),
        ),
        migrations.CreateModel(
            name='InstagramComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='contacts.instagrampost')),
            ],
        ),
        migrations.CreateModel(
            name='InstagramUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_url', models.URLField(verbose_name='URL публикации')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.instagramprofile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'URL публикации',
                'verbose_name_plural': 'URL публикаций',
            },
        ),
    ]
