# Generated by Django 5.0.2 on 2024-03-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_alter_instagramprofile_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramprofile',
            name='url',
            field=models.URLField(help_text='Здесь будет отображаться профиль Instagram', unique=True, verbose_name='Ссылка на инстаграм профиль'),
        ),
    ]
