# Generated by Django 5.0.2 on 2024-03-01 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_alter_instagrampost_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrampost',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contacts.instagramprofile', verbose_name='Профиль'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='post_url',
            field=models.URLField(verbose_name='URL публикации'),
        ),
        migrations.DeleteModel(
            name='InstagramUrl',
        ),
    ]
