# Generated by Django 5.0.2 on 2024-03-08 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_alter_instagramprofile_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='contacts.instagrampost', verbose_name='Пост'),
        ),
        migrations.AlterField(
            model_name='instagramcomment',
            name='profile_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на профиль'),
        ),
        migrations.AlterField(
            model_name='instagramcomment',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='instagramcomment',
            name='username',
            field=models.CharField(blank=True, max_length=255, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='description',
            field=models.TextField(blank=True, default='Описание отсутствует', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на изображение'),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='post_url',
            field=models.URLField(verbose_name='Ссылка на пост'),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_posts', to='contacts.instagramprofile', verbose_name='Профиль'),
        ),
    ]
