# Generated by Django 5.0.2 on 2024-03-01 02:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_instagrampost_profile_alter_instagrampost_post_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instagramcomment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='instagrampost',
            options={'verbose_name': 'Публикация', 'verbose_name_plural': 'Публикации'},
        ),
        migrations.RemoveField(
            model_name='instagramcomment',
            name='post',
        ),
        migrations.AddField(
            model_name='instagramcomment',
            name='post_url',
            field=models.URLField(default=1, verbose_name='URL публикации'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instagramcomment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='instagramcomment',
            name='text',
            field=models.TextField(verbose_name='Текст комментария'),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL фотографии'),
        ),
    ]
