# Generated by Django 5.0.2 on 2024-03-01 02:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_alter_instagramcomment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instagramcomment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='instagrampost',
            options={},
        ),
        migrations.RemoveField(
            model_name='instagramcomment',
            name='post_url',
        ),
        migrations.RemoveField(
            model_name='instagrampost',
            name='profile',
        ),
        migrations.AddField(
            model_name='instagramcomment',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='contacts.instagrampost'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instagramcomment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='instagramcomment',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='post_url',
            field=models.URLField(),
        ),
    ]
