# Generated by Django 5.0.2 on 2024-03-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_alter_instagramcomment_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/', verbose_name='Фотография профиля'),
        ),
    ]
