# Generated by Django 5.0.2 on 2024-03-08 20:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0012_instagramprofile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramprofile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
