# Generated by Django 5.0.2 on 2024-03-08 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0013_instagramprofile_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramcomment',
            name='created_instagram',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания поста'),
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='created_instagram',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания поста'),
        ),
        migrations.AlterField(
            model_name='instagramcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
    ]
