# Generated by Django 5.0.2 on 2024-03-09 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0015_instagramlogin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instagramlogin',
            options={'verbose_name': 'Логин для входа', 'verbose_name_plural': 'Логины для входов'},
        ),
    ]
