# Generated by Django 5.0.2 on 2024-03-09 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0016_alter_instagramlogin_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramprofile',
            name='authorization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorization_profile', to='contacts.instagramlogin', verbose_name='Авторазация аккаунта'),
        ),
    ]
