# Generated by Django 5.0.2 on 2024-03-01 03:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0017_instagramcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instagramcomment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='instagrampost',
            options={},
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='description',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='post_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.instagramprofile'),
        ),
    ]
