# Generated by Django 5.0.2 on 2024-03-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0017_alter_instagramprofile_authorization'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrampost',
            name='count_likes',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество лайков'),
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='count_views',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество просмотров'),
        ),
        migrations.AddField(
            model_name='instagramprofile',
            name='count_followers',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество подписчиков'),
        ),
        migrations.AddField(
            model_name='instagramprofile',
            name='count_posts',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество постов'),
        ),
    ]
