# Generated by Django 5.0.2 on 2024-03-01 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0018_alter_instagramcomment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instagramcomment',
            options={'verbose_name': 'Комментарии', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='instagrampost',
            options={'verbose_name': 'Публикации', 'verbose_name_plural': 'Публикации'},
        ),
        migrations.AlterModelOptions(
            name='instagramprofile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профиль'},
        ),
    ]
