# Generated by Django 5.0.2 on 2024-03-16 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0018_instagrampost_count_likes_instagrampost_count_views_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramcomment',
            name='instagram_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Instagram Comment ID'),
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='instagram_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Instagram Post ID'),
        ),
        migrations.AddField(
            model_name='instagramprofile',
            name='instagram_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Instagram ID'),
        ),
    ]
