# Generated by Django 5.0.2 on 2024-03-01 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0019_alter_instagramcomment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instagramcomment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='instagrampost',
            options={},
        ),
        migrations.AlterModelOptions(
            name='instagramprofile',
            options={},
        ),
    ]
