# Generated by Django 5.0.2 on 2024-03-17 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0020_alter_instagramcomment_instagram_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryTaskErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255)),
                ('error_message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Celery Task Error Log',
                'verbose_name_plural': 'Celery Task Error Logs',
            },
        ),
        migrations.AlterField(
            model_name='instagramprofile',
            name='profile_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='profile_images/', verbose_name='Фотография профиля'),
        ),
    ]
