# Generated by Django 5.0.2 on 2024-02-29 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagrampost',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='instagram_posts'),
        ),
    ]
