# Generated by Django 5.0.2 on 2024-03-06 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0002_instagramsettings_instagramcomment_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramcomment',
            name='profile_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
