# Generated by Django 5.0.2 on 2024-02-29 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0004_remove_instagrampost_image_instagrampost_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagrampost',
            name='image_url',
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='instagram_posts'),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='post_url',
            field=models.URLField(),
        ),
    ]
