# Generated by Django 5.0.2 on 2024-02-29 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0005_remove_instagrampost_image_url_instagrampost_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagrampost',
            name='image',
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
