# Generated by Django 5.0.2 on 2024-02-27 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagramprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='instagramprofile',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='instagramprofile',
            name='username',
        ),
    ]
