# Generated by Django 5.0.2 on 2024-03-05 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_instagramcredentials'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InstagramCredentials',
        ),
    ]
