# Generated by Django 5.0.2 on 2024-02-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_instagramprofile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramprofile',
            name='username',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
