# Generated by Django 5.0.2 on 2024-02-27 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_instagramprofile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagrampost',
            name='created_at',
            field=models.DateTimeField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='image_url',
            field=models.URLField(verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.instagramprofile', verbose_name='Профиль'),
        ),
    ]
