# Generated by Django 5.0.2 on 2024-02-27 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_instagrampost_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagrampost',
            name='image_url',
        ),
        migrations.CreateModel(
            name='InstagramImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(verbose_name='Фотография')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='magazine_image', to='base.instagrampost')),
            ],
        ),
    ]
