# Generated by Django 5.0.2 on 2024-02-27 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_instagrampost_image_url_instagramimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagramimage',
            name='settings',
        ),
        migrations.AddField(
            model_name='instagramimage',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='base.instagrampost'),
            preserve_default=False,
        ),
    ]
