# Generated by Django 5.0.2 on 2024-02-27 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_instagramimage_settings_instagramimage_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instagrampost',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='image_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.instagramprofile'),
        ),
        migrations.DeleteModel(
            name='InstagramImage',
        ),
    ]
