# Generated by Django 5.0.2 on 2024-02-27 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_instagramcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramAuthData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Учетные данные Instagram',
                'verbose_name_plural': 'Учетные данные Instagram',
            },
        ),
    ]
