# Generated by Django 5.0.2 on 2024-02-27 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_instagramauthdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instagramauthdata',
            options={},
        ),
    ]
