# Generated by Django 5.0.2 on 2024-02-27 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_instagramauthdata_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InstagramAuthData',
        ),
        migrations.DeleteModel(
            name='InstagramComment',
        ),
    ]
