# Generated by Django 5.0.2 on 2024-03-01 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_remove_instagrampost_post_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrampost',
            name='post_url',
            field=models.URLField(default=1, verbose_name='URL публикации'),
            preserve_default=False,
        ),
    ]
