# Generated by Django 5.0.2 on 2024-03-01 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_remove_instagrampost_post_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrampost',
            name='post_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на публикацию'),
        ),
    ]
